language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.5
install:
  - pip install coveralls
  - pushd ~
  - git clone https://github.com/pyblish/pyblish-base.git
  - export PYTHONPATH=${PWD}/pyblish-base
  - popd
script:
  - python run_coverage.py
after_success:
  - coveralls
